<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'category_id' => 1,
                'brand_id' => 1,
                'name_ar' => 'جوني ووكر الأحمر',
                'name_en' => 'Johnnie Walker Red Label',
                'bottle_size' => '0.75',
                'alcohol_percentage' => '40.00',
                'price' => '95.00',
                'group_quantity' => 1,
                'description_ar' => 'ويسكي سكوتش مميز',
                'description_en' => 'Premium Scotch whisky',
                'image_url' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'stock_quantity' => 0,
                'created_at' => '2025-11-01 18:11:59',
                'updated_at' => '2025-11-01 18:11:59',
            ],
            [
                'id' => 2,
                'category_id' => 1,
                'brand_id' => 2,
                'name_ar' => 'جاك دانيالز',
                'name_en' => 'Jack Daniels',
                'bottle_size' => '1.00',
                'alcohol_percentage' => '40.00',
                'price' => '120.00',
                'group_quantity' => 1,
                'description_ar' => 'ويسكي تينيسي',
                'description_en' => 'Tennessee whiskey',
                'image_url' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'stock_quantity' => 0,
                'created_at' => '2025-11-01 18:11:59',
                'updated_at' => '2025-11-01 18:11:59',
            ],
            [
                'id' => 3,
                'category_id' => 2,
                'brand_id' => 5,
                'name_ar' => 'فودكا أبسولوت',
                'name_en' => 'Absolut Vodka',
                'bottle_size' => '0.75',
                'alcohol_percentage' => '40.00',
                'price' => '85.00',
                'group_quantity' => 1,
                'description_ar' => 'فودكا سويدية مميزة',
                'description_en' => 'Premium Swedish vodka',
                'image_url' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'stock_quantity' => 0,
                'created_at' => '2025-11-01 18:11:59',
                'updated_at' => '2025-11-01 18:11:59',
            ],
            [
                'id' => 4,
                'category_id' => 4,
                'brand_id' => 8,
                'name_ar' => 'روم باكاردي',
                'name_en' => 'Bacardi Rum',
                'bottle_size' => '0.75',
                'alcohol_percentage' => '37.50',
                'price' => '65.00',
                'group_quantity' => 1,
                'description_ar' => 'روم أبيض',
                'description_en' => 'White rum',
                'image_url' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'stock_quantity' => 0,
                'created_at' => '2025-11-01 18:11:59',
                'updated_at' => '2025-11-01 18:11:59',
            ],
            [
                'id' => 5,
                'category_id' => 5,
                'brand_id' => 9,
                'name_ar' => 'بيرة هاينكن',
                'name_en' => 'Heineken Beer',
                'bottle_size' => '0.33',
                'alcohol_percentage' => '5.00',
                'price' => '12.00',
                'group_quantity' => 6,
                'description_ar' => 'بيرة هولندية',
                'description_en' => 'Dutch beer',
                'image_url' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'stock_quantity' => 0,
                'created_at' => '2025-11-01 18:11:59',
                'updated_at' => '2025-11-01 18:11:59',
            ],
            [
                'id' => 6,
                'category_id' => 1,
                'brand_id' => 1,
                'name_ar' => 'جوني ووكر الأحمر',
                'name_en' => 'Johnnie Walker Red Label',
                'bottle_size' => '0.75',
                'alcohol_percentage' => '40.00',
                'price' => '95.00',
                'group_quantity' => 1,
                'description_ar' => 'ويسكي سكوتش مميز',
                'description_en' => 'Premium Scotch whisky',
                'image_url' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'stock_quantity' => 0,
                'created_at' => '2025-11-01 18:12:39',
                'updated_at' => '2025-11-01 18:12:39',
            ],
            [
                'id' => 7,
                'category_id' => 1,
                'brand_id' => 2,
                'name_ar' => 'جاك دانيالز',
                'name_en' => 'Jack Daniels',
                'bottle_size' => '1.00',
                'alcohol_percentage' => '40.00',
                'price' => '120.00',
                'group_quantity' => 1,
                'description_ar' => 'ويسكي تينيسي',
                'description_en' => 'Tennessee whiskey',
                'image_url' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'stock_quantity' => 0,
                'created_at' => '2025-11-01 18:12:39',
                'updated_at' => '2025-11-01 18:12:39',
            ],
            [
                'id' => 8,
                'category_id' => 2,
                'brand_id' => 5,
                'name_ar' => 'فودكا أبسولوت',
                'name_en' => 'Absolut Vodka',
                'bottle_size' => '0.75',
                'alcohol_percentage' => '40.00',
                'price' => '85.00',
                'group_quantity' => 1,
                'description_ar' => 'فودكا سويدية مميزة',
                'description_en' => 'Premium Swedish vodka',
                'image_url' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'stock_quantity' => 0,
                'created_at' => '2025-11-01 18:12:39',
                'updated_at' => '2025-11-01 18:12:39',
            ],
            [
                'id' => 9,
                'category_id' => 4,
                'brand_id' => 8,
                'name_ar' => 'روم باكاردي',
                'name_en' => 'Bacardi Rum',
                'bottle_size' => '0.75',
                'alcohol_percentage' => '37.50',
                'price' => '65.00',
                'group_quantity' => 1,
                'description_ar' => 'روم أبيض',
                'description_en' => 'White rum',
                'image_url' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'stock_quantity' => 0,
                'created_at' => '2025-11-01 18:12:39',
                'updated_at' => '2025-11-01 18:12:39',
            ],
            [
                'id' => 10,
                'category_id' => 5,
                'brand_id' => 9,
                'name_ar' => 'بيرة هاينكن',
                'name_en' => 'Heineken Beer',
                'bottle_size' => '0.33',
                'alcohol_percentage' => '5.00',
                'price' => '12.00',
                'group_quantity' => 6,
                'description_ar' => 'بيرة هولندية',
                'description_en' => 'Dutch beer',
                'image_url' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'stock_quantity' => 0,
                'created_at' => '2025-11-01 18:12:39',
                'updated_at' => '2025-11-01 18:12:39',
            ],
        ]);
    }
}
